name: 'React Native Build'
description: 'Builds react native app for android platform'
branding:
  icon: 'box'
  color: 'orange'
inputs:
  platform:
    description: 'Platform to build'
    required: false
    default: 'android'
  type:
    description: 'Type can be any of: build | assemble'
    required: false
    default: 'assemble'
  keystore-name:
    description: 'Keystore file name'
    required: true
    default: 'release'
outputs:
  time: # id of output
    description: 'The time started'
runs:
  using: 'composite'
  steps:
    - name: Install npm dependencies
      run: |
        npm install
      shell: bash
    - name: Build Release
      run: |
        echo $SIGNING_KEY | base64 -d > /android/app/${{ inputs.keystore-name }}.keystore
        cd android && ./gradlew ${{ inputs.type }}Release -PMYAPP_UPLOAD_STORE_PASSWORD='${{ env.STORE_PASSWORD }}' -PMYAPP_UPLOAD_KEY_PASSWORD='${{ env.KEY_PASSWORD }}'
      shell: bash
